import { taxonomy, type TaxonomyCategory } from "./taxonomy";
import img0 from '../assets/Hybrid Cotton Seeds.jpg';
import img1 from '../assets/Hybrid Maize Seeds.jpg';
import img2 from '../assets/Paddy Seeds.jpg';
import img3 from '../assets/Wheat Seeds.jpg';
import img4 from '../assets/Bio Fertilizer.jpg';
import img5 from '../assets/NPK19.jpg';
import img6 from '../assets/Urea Fertilizer.jpg';
import img7 from '../assets/Vermicompost.jpeg';
import img8 from '../assets/Insecticide.jpg';
import img9 from '../assets/Fungicide.jpeg';
import img10 from '../assets/Herbicide.jpg';
import img11 from '../assets/Neem Oil Spray.jpg';
import img12 from '../assets/Knapsack Sprayer.jpg';
import img13 from '../assets/Brush Cutter.jpg';
import img14 from '../assets/Power Tiller.jpg';
import img15 from '../assets/Mini Tractor mahindra.jpg';
import img16 from '../assets/Drip Irrigation Kit.jpg';
import img17 from '../assets/Sprinkler Set.jpg';
import img18 from '../assets/HDPE Irrigation Pipe.jpg';
import img19 from '../assets/Water Pump 1HP.jpg';
import img20 from '../assets/Shade Net.jpeg';
import img21 from '../assets/Greenhouse Film.jpeg';
import img22 from '../assets/Cocopeat Block.jpg';
import img23 from '../assets/Seedling Tray.jpg';
import img24 from '../assets/Mango Sapling.jpg';
import img25 from '../assets/Neem Sapling.jpg';
import img26 from '../assets/Garden Tool Kit.jpg';
import img27 from '../assets/Safety Gloves.png';
import img28 from '../assets/PVC Gumboots.jpg';
import img29 from '../assets/soil testing kit.jpg';
import img30 from '../assets/Drone Spraying Service.jpg';


export type Category = TaxonomyCategory;

export const categories: Category[] = taxonomy;

export const crops = [
  {
    slug: "cotton",
    name: "Cotton",
    season: "Kharif",
    image: "https://images.unsplash.com/photo-1595855759920-86582396756a?w=800&q=80",
  },
];

export type Product = {
  slug: string;
  sku: string;
  name: string;
  brand: string;
  category: string;
  crop: string[];
  short: string;
  description: string;
  mrp: number;
  price: number;
  packSize: string;
  rating: number;
  reviews: number;
  stock: "in" | "low" | "out";
  badges: string[];
  benefits: string[];
  usage: string;
  specs: Record<string, string>;
  image: string;
  images: string[];
};

export function formatINR(value: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}

export function findProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export const products: Product[] = [
  {
    slug: "hybrid-cotton-seeds",
    sku: "SA-HYB-5732",
    name: "Hybrid Cotton Seeds",
    brand: "Mahyco",
    category: "seeds",
    crop: ["cotton"],
    short: "BG-II Bt hybrid cotton seeds with high boll retention and excellent fibre quality.",
    description: "Mahyco BG-II Bt hybrid cotton seeds are genetically improved Bollgard-II event (Cry1Ac + Cry2Ab) seeds offering dual-gene resistance against American, spotted, and pink bollworms. These seeds produce sturdy plants with high boll retention, uniform maturity, and superior fibre length (30-32mm). Ideal for Kharif season cultivation across central and southern India. Each 450g packet covers approximately 1 acre with a seed rate of 450-500g per acre. Treated with imidacloprid and carbendazim for protection against sucking pests and soil-borne diseases. Average yield: 12-15 quintals per acre.",
    mrp: 850,
    price: 720,
    packSize: "450g Packet",
    rating: 4.6,
    reviews: 1824,
    stock: "in",
    image: img0,
    images: [img0],
    badges: ["Best Seller", "BG-II"],
    benefits: ["Dual-gene bollworm resistance", "30-32mm fibre length", "12-15 qtl/acre yield", "Dual fungicide treated"],
    usage: "Sow at 450-500g per acre during Kharif (Jun-Jul). Row spacing: 120cm x 60cm. Perform thinning at 15 days. Apply recommended fertiliser dose of 150:75:75 NPK kg/ha.",
    specs: {"Type":"Seeds","Brand":"Mahyco","Pack Size":"450g","Coverage":"1 Acre","Event":"BG-II (Cry1Ac + Cry2Ab)","Yield":"12-15 qtl/acre","Fibre Length":"30-32mm"}
  },
  {
    slug: "hybrid-maize-seeds",
    sku: "SA-HYB-6472",
    name: "Hybrid Maize Seeds",
    brand: "Syngenta",
    category: "seeds",
    crop: ["maize"],
    short: "NK-6240 single-cross hybrid maize with excellent drought tolerance and high grain yield.",
    description: "Syngenta NK-6240 hybrid maize seeds are a premium single-cross hybrid bred for high grain yield (28-32 qtl/acre) and superior stover quality. These seeds show excellent germination vigour, drought tolerance, and genetic resistance to turcicum leaf blight (TLB) and post-flowering stalk rot. Suitable for both Kharif (Jun-Jul) and Rabi (Oct-Nov) seasons. The medium-duration variety matures in 90-95 days with bold golden-yellow semi-dent grains of 280-300 g/TGW. Each 1kg packet covers approximately 1 acre at 18-20 kg seed rate.",
    mrp: 650,
    price: 550,
    packSize: "1kg Packet",
    rating: 4.3,
    reviews: 867,
    stock: "in",
    image: img1,
    images: [img1],
    badges: ["Drought Tolerant", "High Protein"],
    benefits: ["Drought tolerant", "28-32 qtl/acre yield", "TLB resistant", "Bold grains 280g TGW"],
    usage: "Sow at 18-20kg per acre. Row spacing 60cm x 20cm. Apply 120:60:40 NPK kg/ha. Irrigate at critical stages: tasseling and grain filling.",
    specs: {"Type":"Seeds","Brand":"Syngenta","Pack Size":"1kg","Maturity":"90-95 Days","Yield":"28-32 qtl/acre","TGW":"280-300g"}
  },
  {
    slug: "paddy-seeds",
    sku: "SA-PAD-6787",
    name: "Paddy Seeds",
    brand: "Bayer",
    category: "seeds",
    crop: ["paddy"],
    short: "Arize 6444 Gold hybrid paddy seeds with high tillering, blast and BLB resistance.",
    description: "Bayer Arize 6444 Gold hybrid paddy seeds are one of India's most popular rice hybrids, producing plants with strong stems, profuse tillering (18-22 productive tillers), and long panicles (28-32cm) with high grain density (220-250 grains per panicle). Genetically resistant to blast, bacterial leaf blight (BLB), and sheath rot. Suitable for both transplanted and direct-seeded conditions. The 140-145 day duration variety yields 28-32 quintals per acre under proper management. Premium long slender grains with excellent cooking quality.",
    mrp: 1800,
    price: 1550,
    packSize: "10kg Bag",
    rating: 4.4,
    reviews: 2310,
    stock: "in",
    image: img2,
    images: [img2],
    badges: ["High Yield", "Long Grain"],
    benefits: ["Blast + BLB resistant", "28-32 qtl/acre yield", "Long slender grains", "18-22 productive tillers"],
    usage: "Seed rate 8-10kg per acre for transplanting. Nursery 25-30 days before transplanting. Maintain 20x15cm spacing. Apply 120:60:60 NPK kg/ha.",
    specs: {"Type":"Seeds","Brand":"Bayer","Pack Size":"10kg","Duration":"140-145 Days","Yield":"28-32 qtl/acre","Grain Type":"Long Slender"}
  },
  {
    slug: "wheat-seeds",
    sku: "SA-WHE-6870",
    name: "Wheat Seeds",
    brand: "Kaveri",
    category: "seeds",
    crop: ["wheat"],
    short: "HD-3226 wheat variety with excellent rust resistance and high chapati quality score.",
    description: "Kaveri HD-3226 wheat seeds are a recently released high-yielding variety from the HD series, known for excellent chapati-making quality (overall quality score 8.5/10). These seeds produce tall plants (95-105cm) with strong straw, large earheads (12-14cm), and bold amber grains (42-45g TGW). Genetically resistant to yellow rust (stripe rust), brown rust (leaf rust), and loose smut. Ideal for Rabi season cultivation in the north-western plains of India. Matures in 130-135 days with a yield potential of 22-25 quintals per acre.",
    mrp: 1200,
    price: 1050,
    packSize: "30kg Bag",
    rating: 4.5,
    reviews: 1550,
    stock: "in",
    image: img3,
    images: [img3],
    badges: ["Premium", "Rust Resistant"],
    benefits: ["Yellow + brown rust resistant", "22-25 qtl/acre yield", "Superior chapati quality", "Bold amber grains"],
    usage: "Seed rate 100-125kg per hectare. Sow in November (Rabi). Apply 150:60:40 NPK kg/ha. Irrigate at crown root initiation, tillering, flowering and grain filling stages.",
    specs: {"Type":"Seeds","Brand":"Kaveri","Pack Size":"30kg","Duration":"130-135 Days","Yield":"22-25 qtl/acre","Variety":"HD-3226"}
  },
  {
    slug: "bio-fertilizer",
    sku: "SA-BIO-7014",
    name: "Bio Fertilizer",
    brand: "IFFCO",
    category: "fertilizers",
    crop: ["cotton", "maize", "paddy", "wheat", "vegetables", "pulses"],
    short: "IFFCO consortium bio-fertiliser with Rhizobium, Azotobacter, and PSB for soil health.",
    description: "IFFCO bio-fertiliser (NPF 110) is a consortium of beneficial microorganisms including Rhizobium, Azotobacter, Azospirillum, and Phosphate Solubilising Bacteria (PSB) with a minimum viable count of 5x10⁷ CFU/g. It fixes atmospheric nitrogen (20-40 kg N/ha/year) and solubilises fixed phosphorus (15-20 kg P₂O₅/ha) into plant-available forms. Regular use reduces chemical fertiliser requirement by 25-30% while improving soil organic carbon and microbial activity. Suitable for all crops. Each 5kg pack treats 1 acre. Carrier-based formulation in lignite or clay base.",
    mrp: 600,
    price: 500,
    packSize: "5kg Bag",
    rating: 4.2,
    reviews: 645,
    stock: "in",
    image: img4,
    images: [img4],
    badges: ["Organic", "Consortium"],
    benefits: ["Nitrogen fixation 20-40 kg/ha", "Phosphate solubilisation", "25-30% chemical fertiliser reduction", "Improves soil microbial activity"],
    usage: "Mix 5kg per acre with 50kg well-decomposed FYM. Apply near root zone at sowing or through drip irrigation at 2kg/acre at 15-day intervals.",
    specs: {"Type":"Fertilizers","Brand":"IFFCO","Pack Size":"5kg","CFU":"5x10⁷/g","Coverage":"1 Acre","Organisms":"Rhizobium, Azotobacter, PSB"}
  },
  {
    slug: "npk-191919",
    sku: "SA-NPK-6753",
    name: "NPK 19:19:19",
    brand: "Yara",
    category: "fertilizers",
    crop: ["cotton", "maize", "paddy", "wheat", "vegetables", "fruits", "sugarcane"],
    short: "YaraMila 19:19:19 fully water-soluble NPK for fertigation and foliar feeding.",
    description: "YaraMila 19:19:19 is a 100% water-soluble complex fertiliser containing equal proportions of Nitrogen (19%), Phosphorus (19%), and Potassium (19%) along with secondary nutrients (S 2%, Mg 0.5%) and micronutrients (Zn 0.1%, B 0.02%, Fe 0.1%). Each granule dissolves completely in water without residue, making it ideal for fertigation through drip irrigation, sprinklers, or foliar application. Provides balanced nutrition during the vegetative and reproductive stages. Suitable for vegetables, fruits, cereals, cash crops, and ornamentals.",
    mrp: 420,
    price: 360,
    packSize: "1kg Pack",
    rating: 4.5,
    reviews: 3210,
    stock: "in",
    image: img5,
    images: [img5],
    badges: ["Water Soluble", "Fertigation"],
    benefits: ["100% water soluble", "19:19:19 NPK + micronutrients", "Fertigation and foliar ready", "Zero residue"],
    usage: "Foliar spray: 5-10g/L. Fertigation: 3-5kg/acre per split. Apply 4-6 splits at 10-15 day intervals starting from 15 days after sowing.",
    specs: {"Type":"Fertilizers","Brand":"Yara","Pack Size":"1kg","Composition":"19:19:19","Secondary":"S 2%, Mg 0.5%","Micro":"Zn, B, Fe"}
  },
  {
    slug: "urea-fertilizer",
    sku: "SA-URE-5064",
    name: "Urea Fertilizer",
    brand: "IFFCO",
    category: "fertilizers",
    crop: ["cotton", "maize", "paddy", "wheat", "sugarcane"],
    short: "Neem-coated urea 46% N with controlled-release technology for higher efficiency.",
    description: "IFFCO neem-coated urea (NCU) is the primary nitrogenous fertiliser containing 46% nitrogen in amide form. The neem oil coating (1000 ppm) acts as a natural nitrification inhibitor, slowing down nitrogen release from 24-48 hours (uncoated) to 7-10 days, improving nitrogen use efficiency by 15-20%. Reduces denitrification (N₂O gas) and leaching losses by 30%, providing sustained nutrition throughout the crop growth period. Conforms to FCO 1985 specifications. Essential for cereals and cash crops. Available in 50kg HDPE woven bags with inner liner.",
    mrp: 1350,
    price: 1200,
    packSize: "50kg Bag",
    rating: 4.1,
    reviews: 4560,
    stock: "in",
    image: img6,
    images: [img6],
    badges: ["Neem Coated", "Essential"],
    benefits: ["46% Nitrogen (amide form)", "Neem coated slow release", "30% less leaching loss", "15-20% higher N efficiency"],
    usage: "Apply 1-2 bags per acre in 2-3 splits. Basal at sowing, top dressing at tillering and panicle initiation. Incorporate 5-7cm deep to minimise volatilisation loss.",
    specs: {"Type":"Fertilizers","Brand":"IFFCO","Pack Size":"50kg","Nitrogen":"46% N","Coating":"Neem Oil 1000 ppm","Conforms":"FCO 1985"}
  },
  {
    slug: "vermicompost",
    sku: "SA-VER-4955",
    name: "Vermicompost",
    brand: "Organic India",
    category: "fertilizers",
    crop: ["vegetables", "fruits", "ornamental", "pulses", "spices"],
    short: "Earthworm-enriched organic compost with 1.5% NPK for natural soil fertility.",
    description: "Organic India vermicompost is premium-quality organic manure produced by Eisenia fetida earthworms through biodegradation of farmyard waste and cow dung. Rich in macronutrients (N 1.5%, P 0.8%, K 0.7%), micronutrients (Ca, Mg, Zn, Fe, Mn, Cu), beneficial microbes (5x10⁶ CFU/g), and plant growth hormones (auxins, cytokinins). Improves soil aeration, water holding capacity (by 30-40%), and cation exchange capacity. pH 6.8-7.2, organic carbon 12-15%. Suitable for field crops, vegetables, fruits, and ornamental plants as a soil amendment.",
    mrp: 350,
    price: 280,
    packSize: "10kg Bag",
    rating: 4.4,
    reviews: 2890,
    stock: "in",
    image: img7,
    images: [img7],
    badges: ["Organic", "Premium"],
    benefits: ["1.5:0.8:0.7 NPK + micronutrients", "Improves water holding 30-40%", "Plant growth hormones", "12-15% organic carbon"],
    usage: "Apply 2-3 tonnes per acre as basal dose. Mix with topsoil 15 days before sowing. For potted plants, mix 1:3 with garden soil.",
    specs: {"Type":"Fertilizers","Brand":"Organic India","Pack Size":"10kg","NPK":"1.5:0.8:0.7","OC":"12-15%","pH":"6.8-7.2"}
  },
  {
    slug: "insecticide",
    sku: "SA-INS-4252",
    name: "Insecticide",
    brand: "Bayer",
    category: "crop-protection",
    crop: ["cotton", "paddy", "vegetables", "chilli", "groundnut"],
    short: "Imidacloprid 17.8% SL (Confidor) — systemic insecticide for sucking pests.",
    description: "Bayer Confidor (Imidacloprid 17.8% SL) is a neonicotinoid systemic insecticide providing quick knockdown (within 2-3 hours) and long-lasting residual control (12-15 days) of sucking pests including aphids, jassids, thrips, whiteflies (Bemisia tabaci), mealybugs, and plant hoppers. Absorbed by roots and leaves and translocated acropetally via xylem throughout the plant. Exhibits excellent translaminar activity. Safe for predatory insects (coccinellids, chrysoperla) when used at recommended doses. Effective on cotton, rice vegetables, chilli, and groundnut.",
    mrp: 550,
    price: 460,
    packSize: "250ml Bottle",
    rating: 4.6,
    reviews: 4100,
    stock: "in",
    image: img8,
    images: [img8],
    badges: ["Systemic", "Best Seller"],
    benefits: ["Knockdown in 2-3 hours", "12-15 day residual control", "Sucking pest management", "Translaminar activity"],
    usage: "Dilute 2ml per litre of water (400ml/ha). Spray 200-250 litres per acre at first sign of infestation. Do not exceed 2 applications per season. PHI: 7 days.",
    specs: {"Type":"Crop Protection","Brand":"Bayer","Pack Size":"250ml","Active":"Imidacloprid 17.8% SL","Mode":"Systemic","PHI":"7 Days"}
  },
  {
    slug: "fungicide",
    sku: "SA-FUN-7996",
    name: "Fungicide",
    brand: "UPL",
    category: "crop-protection",
    crop: ["vegetables", "fruits", "potato", "grape", "tomato"],
    short: "Mancozeb 75% WP (Dithane M-45) broad-spectrum contact fungicide.",
    description: "UPL Mancozeb 75% WP (equivalent to Dithane M-45) is a broad-spectrum contact fungicide belonging to the dithiocarbamate group. It controls a wide range of fungal diseases including early blight (Alternaria), downy mildew (Peronospora), anthracnose, Septoria leaf spot, Diplocarpon leaf spot, and fruit rot. Forms a protective barrier on plant surfaces, preventing spore germination by inhibiting fungal enzyme systems. Suitable for vegetables, fruits, cereals, and ornamentals. Compatible with most insecticides and fertilisers except strongly alkaline ones. Residual protection of 7-10 days.",
    mrp: 680,
    price: 580,
    packSize: "500g Pack",
    rating: 4.4,
    reviews: 3150,
    stock: "in",
    image: img9,
    images: [img9],
    badges: ["Broad Spectrum", "Contact"],
    benefits: ["Broad-spectrum disease control", "7-10 day protective barrier", "Multi-site action (low resistance risk)", "Tank mix compatible"],
    usage: "Mix 2g per litre of water (1kg/ha). Spray at 10-12 day intervals or at first sign of disease. Ensure complete coverage. PHI: 7 days.",
    specs: {"Type":"Crop Protection","Brand":"UPL","Pack Size":"500g","Active":"Mancozeb 75% WP","Group":"Dithiocarbamate","PHI":"7 Days"}
  },
  {
    slug: "herbicide",
    sku: "SA-HER-8138",
    name: "Herbicide",
    brand: "BASF",
    category: "crop-protection",
    crop: ["cotton", "paddy", "maize", "sugarcane", "orchards"],
    short: "Glyphosate 41% SL (Roundup) non-selective systemic herbicide for total weed control.",
    description: "BASF Glyphosate 41% SL (equivalent to Roundup) is a non-selective, post-emergence systemic herbicide that controls all types of weeds including grasses (Cyperus, Cynodon), sedges, and broadleaf weeds. Absorbed by green foliage and translocated to roots and rhizomes, killing the entire plant including underground reproductive structures within 7-12 days. Rainfast within 4-6 hours. Ideal for non-cropped areas, orchard floors, plantation crops, zero-till farming, and pre-plant weed control. Biodegradable with no soil residual activity. Formulated as isopropylamine salt of glyphosate.",
    mrp: 950,
    price: 800,
    packSize: "1L Bottle",
    rating: 4.5,
    reviews: 5890,
    stock: "in",
    image: img10,
    images: [img10],
    badges: ["Non-Selective", "Systemic"],
    benefits: ["Total weed control incl. rhizomes", "Rainfast in 4-6 hours", "No soil residual activity", "Zero-till compatible"],
    usage: "Mix 30-40ml per litre of water (1.5-2 L/ha in 400-500L water). Spray on actively growing weeds. Avoid spray drift on crop foliage. PHI: N/A (pre-plant use).",
    specs: {"Type":"Crop Protection","Brand":"BASF","Pack Size":"1L","Active":"Glyphosate 41% SL","Salt":"Isopropylamine","Rainfast":"4-6 Hours"}
  },
  {
    slug: "neem-oil-spray",
    sku: "SA-NEE-4611",
    name: "Neem Oil Spray",
    brand: "Organic Agro",
    category: "crop-protection",
    crop: ["vegetables", "fruits", "ornamental", "cotton", "paddy"],
    short: "Cold-pressed neem oil (Azadirachtin 3000 PPM) organic insecticide and miticide.",
    description: "Organic Agro neem oil spray is made from cold-pressed neem seed kernel oil standardised to Azadirachtin content of 3000 PPM (0.3% min). It acts as an antifeedant, repellent, oviposition deterrent, and insect growth regulator disrupting ecdysone hormone for over 200 species of insects and mites. Effective against aphids, whiteflies, caterpillars (Spodoptera, Helicoverpa), leaf miners, thrips, and spider mites. Safe for beneficial insects including honeybees (Apis mellifera), ladybugs, and predatory wasps. Approved for organic farming by NPOP (India) and NOP (USA) standards.",
    mrp: 450,
    price: 380,
    packSize: "500ml Bottle",
    rating: 4.3,
    reviews: 1780,
    stock: "in",
    image: img11,
    images: [img11],
    badges: ["Organic", "NPOP Certified"],
    benefits: ["Azadirachtin 3000 PPM", "IGR + antifeedant action", "Honeybee safe", "NPOP & NOP certified"],
    usage: "Mix 5ml per litre with 0.5ml neutral soap as emulsifier. Spray in evening hours. Repeat every 10-14 days. Shake well before use. PHI: 1 day.",
    specs: {"Type":"Crop Protection","Brand":"Organic Agro","Pack Size":"500ml","Azadirachtin":"3000 PPM (0.3%)","Certification":"NPOP, NOP","PHI":"1 Day"}
  },
  {
    slug: "knapsack-sprayer",
    sku: "SA-KNA-5021",
    name: "Knapsack Sprayer",
    brand: "Neptune",
    category: "farm-machinery",
    crop: ["cotton", "paddy", "vegetables", "orchards"],
    short: "16-litre manual knapsack sprayer with brass pump, adjustable nozzle, and pressure regulator.",
    description: "Neptune 16-litre manual knapsack sprayer (model NK-16) is a heavy-duty sprayer designed for efficient pesticide, herbicide, and foliar fertiliser application. Features a corrosion-resistant brass pump cylinder with leather cup seal delivering 4-5 kg/cm² working pressure, adjustable brass cone nozzle for fine to coarse spray patterns, built-in pressure regulator, and 1.5m delivery hose. The translucent HDPE tank (UV-stabilised) allows liquid level monitoring. Ergonomic padded shoulder straps and waist belt reduce fatigue during extended use. Ideal for small to medium farms, orchards, and vineyards. Includes spare parts kit and maintenance tool.",
    mrp: 2200,
    price: 1850,
    packSize: "16L Capacity",
    rating: 4.3,
    reviews: 3450,
    stock: "in",
    image: img12,
    images: [img12],
    badges: ["Heavy Duty", "Brass Pump"],
    benefits: ["Brass pump with leather seal", "Adjustable cone nozzle", "Pressure regulator included", "UV-stabilised HDPE tank"],
    usage: "Fill max 3/4 tank. Pump 8-10 strokes to pressurise. Adjust nozzle for desired spray pattern. Clean tank and pump with fresh water after every use. Lubricate pump cup with grease monthly.",
    specs: {"Type":"Farm Machinery","Brand":"Neptune","Model":"NK-16","Capacity":"16L","Working Pressure":"4-5 kg/cm²","Material":"HDPE (UV stabilised)"}
  },
  {
    slug: "brush-cutter",
    sku: "SA-BRU-1003",
    name: "Brush Cutter",
    brand: "Husqvarna",
    category: "farm-machinery",
    crop: ["orchards", "plantations", "boundary"],
    short: "Husqvarna 333RJ 33cc petrol brush cutter with Tap'n'Go line feed and metal blade.",
    description: "Husqvarna 333RJ is a professional-grade 33cc petrol-powered brush cutter delivering 1.8 HP at 7000 RPM. Features X-Torq engine technology reducing fuel consumption by 20% and lower exhaust emissions. The solid drive shaft with dual ball bearings ensures smooth, vibration-free operation (5.0 m/s² on handles). Equipped with Tap'n'Go automatic nylon line feed head, 3-tooth metal clearing blade, and a brush clearing blade for heavy vegetation. Smart Start mechanism with combined choke/stop control. Anti-vibration handles (AVS) reduce operator fatigue. Ideal for clearing grass, weeds, underbrush, and thicket.",
    mrp: 8500,
    price: 7200,
    packSize: "Unit (33cc / 1.8 HP)",
    rating: 4.5,
    reviews: 1890,
    stock: "in",
    image: img13,
    images: [img13],
    badges: ["X-Torq", "Low Emission"],
    benefits: ["1.8 HP X-Torq engine", "20% less fuel consumption", "AVS anti-vibration system", "Dual blade + line trimmer"],
    usage: "Mix 50:1 petrol:2-stroke oil. Cold start: choke on, prime, start, then choke off. Wear full PPE. Service air filter every 20 hours. Replace spark plug every 100 hours.",
    specs: {"Type":"Farm Machinery","Brand":"Husqvarna","Model":"333RJ","Engine":"33cc / 1.8 HP","Fuel Mix":"50:1","Vibration":"5.0 m/s²","Weight":"8.2 kg"}
  },
  {
    slug: "power-tiller",
    sku: "SA-POW-3294",
    name: "Power Tiller",
    brand: "VST",
    category: "farm-machinery",
    crop: ["paddy", "vegetables", "orchards", "sugarcane"],
    short: "VST Shakti 130 DI 13 HP diesel power tiller with oil-immersed air cleaner.",
    description: "VST Shakti 130 DI is India's most trusted power tiller, powered by a Greaves Cotton 13 HP (9.7 kW) direct-injection diesel engine at 2200 RPM. Equipped with heavy-duty rotary tiller blades (32 blades) that break tough soil up to 20cm depth and create a fine seedbed in a single pass. Features an oil-immersed dual-stage air cleaner designed for dusty conditions (extends air filter life 3x), 6 forward + 2 reverse sliding mesh gears, dog clutch steering for zero-turn manoeuvrability, and a rear power take-off (PTO) for pump and thresher operations. Fuel consumption: 0.8-1.0 L/hour. Suitable for paddy, vegetables, orchards, and sugarcane cultivation.",
    mrp: 85000,
    price: 78000,
    packSize: "Unit (13 HP Diesel)",
    rating: 4.4,
    reviews: 2240,
    stock: "in",
    image: img14,
    images: [img14],
    badges: ["Diesel", "Best Seller"],
    benefits: ["13 HP DI diesel engine", "20cm deep tilling", "Oil-immersed air cleaner", "Rear PTO included"],
    usage: "Check engine oil, gear oil, air filter oil level daily. Start at medium throttle. Use Gear-1 for tilling, Gear-3 for transport. Grease tines after every use. 250-hour engine oil change.",
    specs: {"Type":"Farm Machinery","Brand":"VST","Model":"Shakti 130 DI","Engine":"13 HP / 2200 RPM","Weight":"385 kg","Fuel Consumption":"0.8-1.0 L/hr","Tilling Depth":"20 cm"}
  },
  {
    slug: "mini-tractor",
    sku: "SA-MIN-3576",
    name: "Mini Tractor",
    brand: "Mahindra",
    category: "farm-machinery",
    crop: ["cotton", "paddy", "sugarcane", "groundnut", "orchards"],
    short: "Mahindra Yuvo 275 DI 30 HP tractor with mPower engine and power steering.",
    description: "Mahindra Yuvo 275 DI is a compact 30 HP (22.4 kW) tractor designed for small and marginal farmers, powered by a 3-cylinder direct-injection diesel engine with Mahindra's mPower technology delivering 12% higher torque backup (30% @ 1500 RPM) and superior fuel efficiency (2.5 L/hour at 50% load). Features power steering, 9-forward + 3-reverse constant mesh transmission with T-20 shuttle shift, multi-speed PTO (540/1000 RPM), and a Category-1 three-point linkage with lifting capacity of 1200 kg. Dual-acting auxiliary hydraulic valve for front-end loader operations. Ground clearance 340mm. Perfect for rotary tilling, disc harrowing, levelling, trailer haulage, and irrigation pump operations.",
    mrp: 425000,
    price: 395000,
    packSize: "Unit (30 HP)",
    rating: 4.6,
    reviews: 4780,
    stock: "in",
    image: img15,
    images: [img15],
    badges: ["Power Steering", "Fuel Efficient"],
    benefits: ["30 HP mPower DI engine", "12% higher torque backup", "Power steering standard", "1200 kg lift capacity"],
    usage: "Engine oil & filter change every 250 hours. Use 9F/3R shuttle for quick direction changes. Engage PTO only at 1500 RPM. Check coolant and hydraulic oil weekly.",
    specs: {"Type":"Farm Machinery","Brand":"Mahindra","Model":"Yuvo 275 DI","Engine":"3-cyl 30 HP DI","Transmission":"9F + 3R Shuttle","Lift Capacity":"1200 kg","PTO":"540/1000 RPM"}
  },
  {
    slug: "drip-irrigation-kit",
    sku: "SA-DRI-9299",
    name: "Drip Irrigation Kit",
    brand: "Jain Irrigation",
    category: "irrigation",
    crop: ["vegetables", "fruits", "cash crops", "sugarcane"],
    short: "Complete 1-acre drip irrigation kit with PC drippers, disc filter, and venturi injector.",
    description: "Jain Irrigation premium drip kit for 1 acre includes: 50mm HDPE mainline (50m), 16mm LLDPE lateral pipes (2400m), online pressure-compensating drippers (4 LPH @ 1 kg/cm², 10,000 drippers), 2-inch disc filter (120 mesh), venturi fertiliser injector (1 inch), control valves, end plugs, and all necessary PVC/PP fittings. Delivers water directly to the root zone, reducing water usage by 40-50% compared to flood irrigation. Coefficient of variation (CV) < 3% ensures uniform water distribution across undulating terrain. Includes detailed installation manual with CAD layout design. Ideal for vegetables, fruits, and cash crops.",
    mrp: 12000,
    price: 10500,
    packSize: "1 Acre Kit",
    rating: 4.5,
    reviews: 2780,
    stock: "in",
    image: img16,
    images: [img16],
    badges: ["Water Saving", "Premium"],
    benefits: ["40-50% water saving", "PC drippers CV<3%", "Fertigation ready with venturi", "Complete install kit"],
    usage: "Install mainline, submain, and laterals with drippers spaced at crop-appropriate intervals. Run 30-60 min daily. Flush laterals monthly. Clean disc filter weekly. Chlorinate at 5ppm every 15 days to prevent bio-clogging.",
    specs: {"Type":"Irrigation","Brand":"Jain Irrigation","Coverage":"1 Acre","Lateral":"16mm LLDPE","Dripper":"4 LPH PC","Filtration":"120 Mesh Disc Filter","Injector":"1 Inch Venturi"}
  },
  {
    slug: "sprinkler-set",
    sku: "SA-SPR-9890",
    name: "Sprinkler Set",
    brand: "KisanKraft",
    category: "irrigation",
    crop: ["vegetables", "nurseries", "lawns", "orchards"],
    short: "Brass impact sprinkler set with 1.2m tripod stand and adjustable arc control.",
    description: "KisanKraft impact sprinkler set (model KK-SP-200) includes a heavy-duty brass impact sprinkler head (3/4 inch inlet) with dual nozzles, 1.2m adjustable aluminium tripod stand with zinc-plated feet, and a 3/4 inch to 1/2 inch brass reducing bush. Covers a diameter of 20-25 metres at 3-4 kg/cm² pressure, with adjustable partial circle (20°-360°) via the diffuser screw. Flow rate: 1000-1200 LPH per sprinkler. Made of corrosion-resistant brass body with stainless steel spring and bearing. Ideal for overhead irrigation of vegetables, nurseries, lawns, and orchards.",
    mrp: 3500,
    price: 2950,
    packSize: "Set with Tripod",
    rating: 4.2,
    reviews: 890,
    stock: "in",
    image: img17,
    images: [img17],
    badges: ["Brass", "Adjustable Arc"],
    benefits: ["20-25m coverage diameter", "Adjustable 20°-360° arc", "Brass body + SS spring", "Tripod stand included"],
    usage: "Connect to 3/4 inch hose or pipe. Operate at 3-4 kg/cm² pressure. Adjust arc via diffuser screw. Winterise by draining before frost. Replace nozzle and spring annually.",
    specs: {"Type":"Irrigation","Brand":"KisanKraft","Model":"KK-SP-200","Coverage":"20-25m","Flow":"1000-1200 LPH","Inlet":"3/4 Inch","Material":"Brass, Aluminium"}
  },
  {
    slug: "hdpe-irrigation-pipe",
    sku: "SA-HDP-6233",
    name: "HDPE Irrigation Pipe",
    brand: "Supreme",
    category: "irrigation",
    crop: ["cotton", "paddy", "vegetables", "sugarcane", "orchards"],
    short: "ISI-marked (IS 4984) 32mm PN 6 HDPE pipe for irrigation mainline and submain.",
    description: "Supreme HDPE irrigation pipe conforms to IS 4984 (BIS standard) manufactured from virgin PE-80 high-density polyethylene. Available in 32mm OD x 2.0mm wall thickness, PN 6 (6 kg/cm² working pressure @ 27°C). Pipe is lightweight (0.19 kg/m), flexible (coilable to 1.2m diameter), and resistant to UV radiation (carbon black 2.5%), chemicals (pH 1-14), and soil acidity. Smooth inner walls (Hazen-Williams coefficient C=150) ensure minimal friction loss. Suitable for buried or above-ground installation in drip and sprinkler irrigation systems. Join by HDPE electrofusion or compression fittings. Coil length: 100m. Pressure test at 1.5x PN (9 kg/cm²) before burial.",
    mrp: 2800,
    price: 2400,
    packSize: "100m Roll (32mm OD x 2.0mm)",
    rating: 4.4,
    reviews: 3650,
    stock: "in",
    image: img18,
    images: [img18],
    badges: ["ISI Marked", "IS 4984"],
    benefits: ["IS 4984 BIS standard", "UV + chemical resistant", "C=150 low friction loss", "PN 6 pressure rated"],
    usage: "Lay in 30-40cm deep trenches for buried installation. Allow 5% slack for thermal expansion. Connect using electrofusion couplers or compression fittings. Pressure test at 9 kg/cm² (1.5x PN) for 1 hour before backfill.",
    specs: {"Type":"Irrigation","Brand":"Supreme","Standard":"IS 4984","Size":"32mm OD x 2.0mm","Rating":"PN 6","Weight":"0.19 kg/m","Material":"PE-80 HDPE","UV":"2.5% Carbon Black"}
  },
  {
    slug: "water-pump-1hp",
    sku: "SA-WAT-2403",
    name: "Water Pump 1HP",
    brand: "Kirloskar",
    category: "irrigation",
    crop: ["cotton", "paddy", "vegetables", "sugarcane"],
    short: "Kirloskar 1HP (0.75kW) monoblock centrifugal pump, max head 25m, discharge 3000 LPH.",
    description: "Kirloskar 1HP (0.75 kW) monoblock centrifugal pump (model 1C1B) is a reliable and energy-efficient water pumping solution for agricultural irrigation. Cast iron volute casing with dynamically balanced bronze (Cu 85%) or SS304 impeller ensures long life and corrosion resistance. Maximum total head: 25 metres. Maximum discharge: 3250 LPH at 10m head, 2400 LPH at 20m head. Suction lift: 6 metres. Single-phase 230V AC motor (2-pole, 2900 RPM) with class-B insulation, built-in thermal overload protector (auto-reset), and drip-proof enclosure. Suitable for lifting water from open wells, borewells (4 inch min), and reservoirs for irrigation. Delivery size: 1 inch. Suction size: 1 inch.",
    mrp: 6500,
    price: 5600,
    packSize: "Unit (1 HP / 0.75 kW)",
    rating: 4.5,
    reviews: 5230,
    stock: "in",
    image: img19,
    images: [img19],
    badges: ["Energy Efficient", "ISI"],
    benefits: ["1 HP 2900 RPM motor", "3250 LPH max discharge", "25m max head", "Thermal overload protection"],
    usage: "Prime casing before start. Ensure foot valve submerged. Never run dry >1 minute. Use 1 inch suction pipe (non-collapsible). Install at max 6m from water source. Drain water in freezing conditions.",
    specs: {"Type":"Irrigation","Brand":"Kirloskar","Model":"1C1B","Power":"1 HP / 0.75 kW","Max Head":"25m","Max Discharge":"3250 LPH","Suction":"1 Inch","Delivery":"1 Inch","RPM":"2900"}
  },
  {
    slug: "shade-net-75",
    sku: "SA-SHA-2712",
    name: "Shade Net (75%)",
    brand: "Garware",
    category: "protected-cultivation",
    crop: ["nurseries", "ornamental", "spices", "vegetables"],
    short: "UV-stabilised 75% HDPE shade net with 5-year warranty for nursery and protected cultivation.",
    description: "Garware 75% shade net is woven from 100% UV-stabilised HDPE monofilament yarn (denier 200-250) with a 5-year UV degradation warranty (<5% strength loss/year). The 75% shading density (25% light transmission) is ideal for shade-loving plants like turmeric, ginger, cardamom, lettuce, spinach, and nursery seedlings. Reduces heat stress by 5-8°C under canopy, conserves soil moisture by reducing evaporation by 40%, and protects crops from birds, hail, and heavy rain. Lightweight (85 gsm) with reinforced edges and aluminium grommets at 1m intervals for secure fastening. Roll size: 4m wide x 25m long (100 sqm).",
    mrp: 3200,
    price: 2700,
    packSize: "100sqm Roll (4m x 25m)",
    rating: 4.4,
    reviews: 3120,
    stock: "in",
    image: img20,
    images: [img20],
    badges: ["UV Stabilised", "5 Year Warranty"],
    benefits: ["75% shade (25% light transmission)", "5-year UV warranty", "Reduces temperature 5-8°C", "Grommets at 1m spacing"],
    usage: "Install on GI pipe or bamboo frame at 3°-5° slope for rain runoff. Secure with 6mm rope through grommets at 1m intervals. Overlap 15cm at joints. Tighten monthly to maintain tension.",
    specs: {"Type":"Protected Cultivation","Brand":"Garware","Shade":"75%","Size":"4m x 25m","Weight":"85 gsm","Warranty":"5 Years UV","Material":"HDPE Monofilament"}
  },
  {
    slug: "greenhouse-film",
    sku: "SA-GRE-3686",
    name: "Greenhouse Film",
    brand: "Jain",
    category: "protected-cultivation",
    crop: ["vegetables", "flowers", "nurseries", "strawberry"],
    short: "200-micron 3-layer co-extruded UV + IR + anti-drip greenhouse cladding film.",
    description: "Jain 200-micron greenhouse film is a 3-layer co-extruded polyethylene sheet with UV stabilisers (anti-UV up to 6 months life), anti-drip/anti-fog additives on the inner surface, and IR (infrared) thermal blockers on the outer layer. Provides 90% photosynthetically active radiation (PAR) transmission while diffusing direct sunlight for uniform crop growth, eliminating hot spots. The anti-drip layer prevents condensation droplets from falling on plant foliage, reducing the incidence of botrytis and other fungal diseases by 60%. IR blocking reduces night-time heat loss by 25-30%, maintaining 2-4°C warmer nights. Suitable for naturally ventilated polyhouses and hi-tech greenhouses. Roll: 8m x 25m (200 sqm).",
    mrp: 8000,
    price: 6800,
    packSize: "200sqm Roll (8m x 25m)",
    rating: 4.3,
    reviews: 1670,
    stock: "in",
    image: img21,
    images: [img21],
    badges: ["Anti-Drip", "IR Block"],
    benefits: ["90% PAR transmission", "Anti-drip anti-fog inner layer", "IR thermal retention 25-30%", "3-layer co-extruded"],
    usage: "Install with printed side facing out. Drape over frame, secure with aluminium profile and wiggle wire. Keep film taut. Slope 15° minimum for rain runoff. Avoid dragging on ground during installation.",
    specs: {"Type":"Protected Cultivation","Brand":"Jain","Thickness":"200 Micron","Size":"8m x 25m","Layers":"3-Layer Co-extruded","PAR Transmission":"90%","Features":"UV + Anti-drip + IR"}
  },
  {
    slug: "cocopeat-block",
    sku: "SA-COC-9762",
    name: "Cocopeat Block",
    brand: "Ugaoo",
    category: "urban-gardening",
    crop: ["vegetables", "ornamental", "nurseries", "hydroponics"],
    short: "Compressed cocopeat block 5kg, expands to 40L — pH 6.0, EC <0.5 mS/cm.",
    description: "Ugaoo cocopeat block is made from washed, buffered, and sieved (<5mm) coconut coir pith processed with fresh water to reduce electrical conductivity (EC <0.5 mS/cm, ideal for all plants). A single 5kg block expands with 4-5 litres of water to yield 40 litres of fluffy, pH-neutral (6.0-6.5) growing medium. Water holding capacity: 450-500 ml/L (8-10x dry weight). Air-filled porosity: 30-35% for optimal root aeration. Ideal for seed germination, potting mixes, hydroponics, and soil amendment. Low EC ensures safe use with sensitive seedlings and tissue culture plants.",
    mrp: 350,
    price: 280,
    packSize: "5kg Block (Expands to 40L)",
    rating: 4.3,
    reviews: 2340,
    stock: "in",
    image: img22,
    images: [img22],
    badges: ["Expands 8x", "Low EC"],
    benefits: ["Expands to 40L from 5kg", "EC <0.5 mS/cm low salt", "pH 6.0-6.5 optimal range", "450-500 ml/L water holding"],
    usage: "Place block in container, add 4-5L water, let expand 30 min, break apart with hand. For seed germination: mix 3:1 cocopeat:perlite. For potting: mix 1:1:1 cocopeat:compost:garden soil.",
    specs: {"Type":"Urban Gardening","Brand":"Ugaoo","Weight":"5kg","Expanded Volume":"40L","EC":"<0.5 mS/cm","pH":"6.0-6.5","WHC":"450-500 ml/L","Porosity":"30-35%"}
  },
  {
    slug: "seedling-tray",
    sku: "SA-SEE-3301",
    name: "Seedling Tray",
    brand: "KisanKraft",
    category: "urban-gardening",
    crop: ["vegetables", "flowers", "nurseries"],
    short: "98-cell plastic protray with drainage holes, root guides, and UV stabilisers.",
    description: "KisanKraft 98-cell seedling tray (standard 540mm x 280mm size) made from premium food-grade virgin PP plastic (0.8mm thickness) with UV stabilisers for extended outdoor life. Each cell: 40mm depth, 30mm top diameter tapering to 15mm bottom, with a 5mm drainage hole and 4 internal vertical ribs that guide roots straight down, preventing root circling and promoting air pruning. Stackable design (25 trays per stack) for efficient nursery space utilisation. Compatible with most automatic seeders (Veldman, Hamilton) and transplanting equipment. Reusable for 3-4 cropping seasons (2-3 years) with proper cleaning and sterilization.",
    mrp: 250,
    price: 195,
    packSize: "98-Cell Tray",
    rating: 4.2,
    reviews: 4560,
    stock: "in",
    image: img23,
    images: [img23],
    badges: ["Reusable", "UV Stabilised"],
    benefits: ["98 cells with root guide ribs", "Air-pruning design", "UV-stabilised PP plastic", "3-4 season reusable"],
    usage: "Fill with cocopeat + perlite (3:1), sow 1 seed per cell at 0.5cm depth. Keep moist with fine mist. Transplant seedlings at 3-4 true leaf stage. Sterilise between batches with 0.5% sodium hypochlorite.",
    specs: {"Type":"Urban Gardening","Brand":"KisanKraft","Cells":"98","Size":"540x280mm","Cell Depth":"40mm","Material":"Virgin PP","Thickness":"0.8mm"}
  },
  {
    slug: "mango-sapling",
    sku: "SA-MAN-4916",
    name: "Mango Sapling",
    brand: "Nursery Fresh",
    category: "saplings-plants",
    crop: ["orchard"],
    short: "Grafted Alphonso mango (Mangifera indica) sapling, 12-18 months, polybag grown.",
    description: "Nursery Fresh Alphonso mango (Mangifera indica) saplings are grafted by the veneer grafting method onto resistant rootstocks (Vellaikulumban or Bappakkai) for enhanced disease resistance and dwarfing. Each sapling is 12-18 months old from grafting, 75-90 cm tall, with a 6-8mm graft union, and grown in a 6x8 inch (20cmØ) polybag with well-developed root system. Starts commercial bearing in 3-4 years after field planting, reaching full production by year 6-7. Alphonso (Hapus) produces medium-sized (200-300g) golden-yellow fruits with a characteristic sweet aroma, rich flavour, and fibreless pulp. Disease-free stock certified under the National Horticulture Mission (NHM) guidelines. Average yield: 150-200 fruits per tree at maturity.",
    mrp: 150,
    price: 110,
    packSize: "Per Sapling (6x8 inch Polybag)",
    rating: 4.5,
    reviews: 3450,
    stock: "in",
    image: img24,
    images: [img24],
    badges: ["Grafted", "Premium Variety"],
    benefits: ["Alphonso (Hapus) premium variety", "Veneer grafted on resistant rootstock", "Bearing in 3-4 years", "NHM disease-free certified"],
    usage: "Plant in 3x3x3ft pit with 15kg FYM + 1kg bonemeal. Spacing: 8m x 8m. Water weekly for first 2 years. Apply 100:50:100g NPK/tree/year increasing to 500:250:500g at maturity.",
    specs: {"Type":"Saplings & Plants","Brand":"Nursery Fresh","Age":"12-18 Months","Height":"75-90 cm","Variety":"Alphonso (Hapus)","Graft Type":"Veneer","Rootstock":"Vellaikulumban"}
  },
  {
    slug: "neem-sapling",
    sku: "SA-NEE-9832",
    name: "Neem Sapling",
    brand: "Green Nursery",
    category: "saplings-plants",
    crop: ["boundary", "agroforestry"],
    short: "Fast-growing neem (Azadirachta indica) sapling 8-12 months, 60-90cm tall.",
    description: "Green Nursery neem (Azadirachta indica) saplings are grown from high-germination (>85%) seeds collected from identified plus trees (30-40 years old, high azadirachtin content). Each sapling is 8-12 months old, 60-90 cm tall, with a 5-8mm stem diameter, and grown in a 5x7 inch polybag. Neem is a fast-growing, drought-tolerant (survives 8-10 months dry season) evergreen tree reaching 15-20m at maturity. Provides valuable timber (0.6-0.8 g/cc density), neem oil (30-40% from kernels, Azadirachtin 2000-3000 ppm), and natural pesticide (leaf extract). Excellent for boundary plantation at 5m spacing, windbreaks in arid zones, and agroforestry intercropping with arable crops. Expected economic life: 40-50 years.",
    mrp: 80,
    price: 55,
    packSize: "Per Sapling (5x7 inch Polybag)",
    rating: 4.6,
    reviews: 8900,
    stock: "in",
    image: img25,
    images: [img25],
    badges: ["Fast Growing", "Drought Tolerant"],
    benefits: ["Drought tolerant (8-10 months)", "15-20m mature height", "Neem oil 30-40% from kernels", "Excellent windbreak species"],
    usage: "Plant at 5m spacing for boundary, 8m x 8m for plantation. Dig 45cm³ pit, fill with topsoil + 5kg FYM. Water weekly first year. Prune lower branches from year 3 for timber quality.",
    specs: {"Type":"Saplings & Plants","Brand":"Green Nursery","Age":"8-12 Months","Height":"60-90 cm","Species":"Azadirachta indica","Mature Height":"15-20m"}
  },
  {
    slug: "garden-tool-kit",
    sku: "SA-GAR-3791",
    name: "Garden Tool Kit",
    brand: "Falcon",
    category: "farm-accessories",
    crop: ["vegetables", "ornamental", "kitchen garden"],
    short: "7-piece stainless steel garden tool set with ergonomic handles and canvas bag.",
    description: "Falcon 7-piece garden tool kit includes: stainless steel trowel (28cm), transplanting trowel (28cm), hand fork (25cm) with 4 tines, weeder with v-cutter (30cm), pruning shears (8 inch, SK-5 steel blade with sap groove), 3-prong cultivator (28cm), and a brass watering nozzle with thumb control. All tool heads are 3CR13 stainless steel (HRC 48-52 hardness) with oiled teak wood handles. Shears have bi-material rubberised grips. Includes a 600-denier heavy-duty canvas storage bag with 7 individual slots and a roll-top closure. Ideal for kitchen gardening, terrace gardening, nursery work, and landscaping.",
    mrp: 1500,
    price: 1250,
    packSize: "7-Piece Set with Canvas Bag",
    rating: 4.4,
    reviews: 2780,
    stock: "in",
    image: img26,
    images: [img26],
    badges: ["Set of 7", "Stainless"],
    benefits: ["7 tools + watering nozzle", "3CR13 stainless steel HRC 48-52", "Teak wood + rubberised handles", "Canvas roll-top storage bag"],
    usage: "Clean with dry cloth after use, oil metal parts lightly. Pruning shears: cut cleanly do not twist. Sharpen shears with fine file annually. Store in canvas bag in dry location.",
    specs: {"Type":"Farm Accessories","Brand":"Falcon","Pieces":"7","Tool Steel":"3CR13 Stainless HRC 48-52","Handle":"Teak Wood / Bi-material","Bag":"600D Canvas with Roll-top"}
  },
  {
    slug: "safety-gloves",
    sku: "SA-SAF-5103",
    name: "Safety Gloves",
    brand: "Venus",
    category: "farm-accessories",
    crop: ["cotton", "paddy", "vegetables", "orchards"],
    short: "13-gauge nitrile-coated cotton safety gloves, cut level A2, chemical splash resistant.",
    description: "Venus safety gloves (model VG-620) feature a 13-gauge seamless 100% cotton liner (half-thumb crotch) with black nitrile micro-foam coating on palm and fingers (70% coverage) for superior grip in wet and oily conditions. Cut resistance: EN388 Level A2 (coupe test 2000+ cycles). Abrasion resistance: Level 4 (8000+ cycles). Puncture resistance: Level 2 (100+ Newtons). The nitrile coating provides protection against dilute pesticides, herbicides, fertilisers, and animal waste. Elastic knit wrist prevents debris entry. Breathable cotton back reduces hand perspiration. Available in sizes 7 (M), 8 (L), 9 (XL). Suitable for pesticide handling, pruning, thorny plant handling, fencing, and general farm maintenance.",
    mrp: 180,
    price: 140,
    packSize: "Pair (Size L - 8)",
    rating: 4.3,
    reviews: 7450,
    stock: "in",
    image: img27,
    images: [img27],
    badges: ["Nitrile Coated", "EN388 Rated"],
    benefits: ["Cut level A2 (2000+ cycles)", "Nitrile micro-foam grip", "Chemical splash protection", "Breathable cotton back"],
    usage: "Select snug fit (neither tight nor loose). Wash with soap water after pesticide use; air dry. Replace if torn, punctured, or if liner is visible. Double glove for extended chemical handling.",
    specs: {"Type":"Farm Accessories","Brand":"Venus","Model":"VG-620","Material":"Cotton 13G + Nitrile","Sizes":"7/M, 8/L, 9/XL","EN388":"A2, Abrasion 4, Puncture 2"}
  },
  {
    slug: "pvc-gumboots",
    sku: "SA-PVC-8434",
    name: "PVC Gumboots",
    brand: "Liberty",
    category: "farm-accessories",
    crop: ["paddy", "vegetables", "dairy", "fisheries"],
    short: "Full-length PVC gum boot with steel toe (200J) and slip-resistant outsole for farm use.",
    description: "Liberty full-length PVC gum boot (model LB-100) provides complete lower-leg protection in wet, muddy, and chemical-laden farm environments. Made from single-moulded high-grade PVC compound (Shore A 65±5) with no seams or leaks. Steel toe cap conforms to IS 5852:2006 / EN 345 withstands 200J impact (200N compression). Slip-resistant outsole with 20mm deep self-cleaning treads (lug pattern) offers superior grip on wet surfaces (certified SRA slip rating). Height: 36cm (14 inch). Removable EVA cushioned insole with activated charcoal for odour control. Resistant to fertilisers (NPK solutions), pesticides (organophosphates), diesel, and animal waste. Suitable for paddy farming, vegetable cultivation, dairy operations, and aquaculture.",
    mrp: 550,
    price: 450,
    packSize: "Pair (Size 8 - UK 8 / EU 42)",
    rating: 4.4,
    reviews: 11200,
    stock: "in",
    image: img28,
    images: [img28],
    badges: ["Steel Toe", "Slip Resistant"],
    benefits: ["Steel toe 200J impact protection", "SRA slip-rated outsole", "Chemical resistant PVC", "Removable EVA insole"],
    usage: "Wash with water after use, dry in shade away from direct sunlight. Apply silicone spray monthly to prevent PVC cracking. Replace if sole tread depth <3mm or if any puncture in waterproof layer.",
    specs: {"Type":"Farm Accessories","Brand":"Liberty","Model":"LB-100","Height":"36cm / 14 inch","Material":"PVC (Shore A 65)","Toe":"Steel IS 5852 / EN 345","Sizes":"UK 6-12 / EU 39-47"}
  },
  {
    slug: "soil-testing-kit",
    sku: "SA-SOI-4464",
    name: "Soil Testing Kit",
    brand: "AgroLab",
    category: "soil-water-testing",
    crop: ["cotton", "paddy", "wheat", "vegetables", "sugarcane"],
    short: "Portable soil testing kit for pH, NPK, EC analysis — 15-minute on-farm results.",
    description: "AgroLab portable soil testing kit (model AL-200) enables on-farm semi-quantitative analysis of soil pH, available Nitrogen (N), Phosphorus (P₂O₅), Potassium (K₂O), and Electrical Conductivity (EC). Kit includes: 5 reagent bottles (pH indicator, N reagent, P reagent 1 & 2, K reagent), colour comparator chart with 8-10 colour steps per parameter, 6 glass test tubes with rubber stoppers, 2 graduated droppers (1ml & 5ml), 10g measuring spoon, filter papers, pH reference solution, EC probe (analogue), and a 32-page instruction manual in English and Hindi. Results in 5-20 minutes per test (pH: 5 min, N: 20 min, P: 15 min, K: 15 min, EC: 2 min). No laboratory equipment or electricity required. Test range: pH 4.0-9.5, N 10-300 kg/ha, P 5-100 kg/ha, K 20-400 kg/ha. Helps farmers make informed fertiliser recommendations. Each kit performs approximately 50 tests per parameter.",
    mrp: 1200,
    price: 990,
    packSize: "Kit with Manual (50 tests/parameter)",
    rating: 4.1,
    reviews: 6780,
    stock: "in",
    image: img29,
    images: [img29],
    badges: ["Portable", "50 Tests"],
    benefits: ["pH, N, P, K, EC analysis", "5-20 min per test", "50 tests per parameter", "Hindi + English manual"],
    usage: "Collect soil from 5 random spots (10-15cm depth), mix thoroughly. Take 10g sample + reagents as per manual. Match colour development with chart. Interpret fertiliser recommendation from manual tables.",
    specs: {"Type":"Soil & Water Testing","Brand":"AgroLab","Model":"AL-200","Tests":"pH, N, P, K, EC","Range pH":"4.0-9.5","Range N":"10-300 kg/ha","Test Capacity":"50 tests/parameter","Manual":"Hindi + English"}
  },
  {
    slug: "drone-spraying-service",
    sku: "SA-DRO-1020",
    name: "Drone Spraying Service",
    brand: "AgriFly",
    category: "services",
    crop: ["cotton", "paddy", "sugarcane", "orchards"],
    short: "Professional RTK-GPS drone spraying service — 1 acre in 10 min, 30% less chemical.",
    description: "AgriFly professional drone spraying service utilises DJI Agras T40 agricultural drones with 40-litre liquid tank capacity, RTK GPS (2.5cm precision), and centrifugal atomised spray nozzles generating uniform droplet size (130-250 microns). Each sortie covers 1 acre in 8-10 minutes with swath width of 7m at 4m height. Chemical usage reduced by 30% compared to manual spraying due to precise targeted application and minimal drift (<5% at 8 km/h crosswind). Terrain-following radar (TFR) enables safe operation on slopes up to 30°. Suitable for all crops: paddy, cotton, sugarcane, orchards, and plantations. Service package includes: certified drone pilot, spray solution preparation, real-time flight tracking, and post-application digital report with coverage map and chemical usage analytics. Booking requires 48-hour advance notice. Minimum order: 2 acres.",
    mrp: 2500,
    price: 2000,
    packSize: "Per Acre Service (Min 2 Acres)",
    rating: 4.5,
    reviews: 4230,
    stock: "in",
    image: img30,
    images: [img30],
    badges: ["Precision", "RTK GPS"],
    benefits: ["1 acre in 10 min coverage", "30% less chemical + less drift", "RTK GPS 2.5cm precision", "Digital coverage report"],
    usage: "Book 48hr in advance on website or call. Clear field of overhead wires and tall obstacles. Ensure wind <15 km/h. No standing water required (drone operates on battery). Payment via UPI, card, or credit.",
    specs: {"Type":"Agricultural Services","Brand":"AgriFly","Drone":"DJI Agras T40","Tank Capacity":"40L","Coverage Rate":"1 acre/10 min","Swath Width":"7m @ 4m height","GPS Accuracy":"RTK ±2.5cm","Min Order":"2 Acres"}
  },
];
