/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DealerRegistrationRouteImport } from './routes/dealer-registration'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as LegalPageRouteImport } from './routes/legal.$page'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AuthWishlistRouteImport } from './routes/_auth.wishlist'
import { Route as AuthWarehouseRouteImport } from './routes/_auth.warehouse'
import { Route as AuthSupportRouteImport } from './routes/_auth.support'
import { Route as AuthSalesRouteImport } from './routes/_auth.sales'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthOrdersRouteImport } from './routes/_auth.orders'
import { Route as AuthMarketingRouteImport } from './routes/_auth.marketing'
import { Route as AuthFarmerRouteImport } from './routes/_auth.farmer'
import { Route as AuthDistributorRouteImport } from './routes/_auth.distributor'
import { Route as AuthDeliveryRouteImport } from './routes/_auth.delivery'
import { Route as AuthDealerRouteImport } from './routes/_auth.dealer'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthContentRouteImport } from './routes/_auth.content'
import { Route as AuthAccountsRouteImport } from './routes/_auth.accounts'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerRegistrationRoute = DealerRegistrationRouteImport.update({
  id: '/dealer-registration',
  path: '/dealer-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPageRoute = LegalPageRouteImport.update({
  id: '/legal/$page',
  path: '/legal/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AuthWishlistRoute = AuthWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWarehouseRoute = AuthWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSupportRoute = AuthSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSalesRoute = AuthSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMarketingRoute = AuthMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFarmerRoute = AuthFarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDistributorRoute = AuthDistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDeliveryRoute = AuthDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDealerRoute = AuthDealerRouteImport.update({
  id: '/dealer',
  path: '/dealer',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContentRoute = AuthContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountsRoute = AuthAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dealer-registration': typeof DealerRegistrationRoute
  '/knowledge': typeof KnowledgeRoute
  '/signin': typeof SigninRoute
  '/track': typeof TrackRoute
  '/accounts': typeof AuthAccountsRoute
  '/content': typeof AuthContentRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dealer': typeof AuthDealerRoute
  '/delivery': typeof AuthDeliveryRoute
  '/distributor': typeof AuthDistributorRoute
  '/farmer': typeof AuthFarmerRoute
  '/marketing': typeof AuthMarketingRoute
  '/orders': typeof AuthOrdersRoute
  '/profile': typeof AuthProfileRoute
  '/sales': typeof AuthSalesRoute
  '/support': typeof AuthSupportRoute
  '/warehouse': typeof AuthWarehouseRoute
  '/wishlist': typeof AuthWishlistRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/content': typeof AdminContentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/$page': typeof LegalPageRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dealer-registration': typeof DealerRegistrationRoute
  '/knowledge': typeof KnowledgeRoute
  '/signin': typeof SigninRoute
  '/track': typeof TrackRoute
  '/accounts': typeof AuthAccountsRoute
  '/content': typeof AuthContentRoute
  '/dashboard': typeof AuthDashboardRoute
  '/dealer': typeof AuthDealerRoute
  '/delivery': typeof AuthDeliveryRoute
  '/distributor': typeof AuthDistributorRoute
  '/farmer': typeof AuthFarmerRoute
  '/marketing': typeof AuthMarketingRoute
  '/orders': typeof AuthOrdersRoute
  '/profile': typeof AuthProfileRoute
  '/sales': typeof AuthSalesRoute
  '/support': typeof AuthSupportRoute
  '/warehouse': typeof AuthWarehouseRoute
  '/wishlist': typeof AuthWishlistRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/content': typeof AdminContentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/$page': typeof LegalPageRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/dealer-registration': typeof DealerRegistrationRoute
  '/knowledge': typeof KnowledgeRoute
  '/signin': typeof SigninRoute
  '/track': typeof TrackRoute
  '/_auth/accounts': typeof AuthAccountsRoute
  '/_auth/content': typeof AuthContentRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/dealer': typeof AuthDealerRoute
  '/_auth/delivery': typeof AuthDeliveryRoute
  '/_auth/distributor': typeof AuthDistributorRoute
  '/_auth/farmer': typeof AuthFarmerRoute
  '/_auth/marketing': typeof AuthMarketingRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/sales': typeof AuthSalesRoute
  '/_auth/support': typeof AuthSupportRoute
  '/_auth/warehouse': typeof AuthWarehouseRoute
  '/_auth/wishlist': typeof AuthWishlistRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/content': typeof AdminContentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/$page': typeof LegalPageRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/catalog'
    | '/checkout'
    | '/contact'
    | '/dealer-registration'
    | '/knowledge'
    | '/signin'
    | '/track'
    | '/accounts'
    | '/content'
    | '/dashboard'
    | '/dealer'
    | '/delivery'
    | '/distributor'
    | '/farmer'
    | '/marketing'
    | '/orders'
    | '/profile'
    | '/sales'
    | '/support'
    | '/warehouse'
    | '/wishlist'
    | '/admin/catalog'
    | '/admin/employees'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/reports'
    | '/admin/content'
    | '/auth/login'
    | '/auth/register'
    | '/blog/$slug'
    | '/legal/$page'
    | '/products/$slug'
    | '/admin/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/checkout'
    | '/contact'
    | '/dealer-registration'
    | '/knowledge'
    | '/signin'
    | '/track'
    | '/accounts'
    | '/content'
    | '/dashboard'
    | '/dealer'
    | '/delivery'
    | '/distributor'
    | '/farmer'
    | '/marketing'
    | '/orders'
    | '/profile'
    | '/sales'
    | '/support'
    | '/warehouse'
    | '/wishlist'
    | '/admin/catalog'
    | '/admin/employees'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/reports'
    | '/admin/content'
    | '/auth/login'
    | '/auth/register'
    | '/blog/$slug'
    | '/legal/$page'
    | '/products/$slug'
    | '/admin'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/admin'
    | '/catalog'
    | '/checkout'
    | '/contact'
    | '/dealer-registration'
    | '/knowledge'
    | '/signin'
    | '/track'
    | '/_auth/accounts'
    | '/_auth/content'
    | '/_auth/dashboard'
    | '/_auth/dealer'
    | '/_auth/delivery'
    | '/_auth/distributor'
    | '/_auth/farmer'
    | '/_auth/marketing'
    | '/_auth/orders'
    | '/_auth/profile'
    | '/_auth/sales'
    | '/_auth/support'
    | '/_auth/warehouse'
    | '/_auth/wishlist'
    | '/admin/catalog'
    | '/admin/employees'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/reports'
    | '/admin/content'
    | '/auth/login'
    | '/auth/register'
    | '/blog/$slug'
    | '/legal/$page'
    | '/products/$slug'
    | '/admin/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DealerRegistrationRoute: typeof DealerRegistrationRoute
  KnowledgeRoute: typeof KnowledgeRoute
  SigninRoute: typeof SigninRoute
  TrackRoute: typeof TrackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LegalPageRoute: typeof LegalPageRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer-registration': {
      id: '/dealer-registration'
      path: '/dealer-registration'
      fullPath: '/dealer-registration'
      preLoaderRoute: typeof DealerRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$page': {
      id: '/legal/$page'
      path: '/legal/$page'
      fullPath: '/legal/$page'
      preLoaderRoute: typeof LegalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/wishlist': {
      id: '/_auth/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthWishlistRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/warehouse': {
      id: '/_auth/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AuthWarehouseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/support': {
      id: '/_auth/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthSupportRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sales': {
      id: '/_auth/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthSalesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/marketing': {
      id: '/_auth/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthMarketingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/farmer': {
      id: '/_auth/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof AuthFarmerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/distributor': {
      id: '/_auth/distributor'
      path: '/distributor'
      fullPath: '/distributor'
      preLoaderRoute: typeof AuthDistributorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/delivery': {
      id: '/_auth/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AuthDeliveryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dealer': {
      id: '/_auth/dealer'
      path: '/dealer'
      fullPath: '/dealer'
      preLoaderRoute: typeof AuthDealerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/content': {
      id: '/_auth/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthContentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts': {
      id: '/_auth/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthAccountsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountsRoute: typeof AuthAccountsRoute
  AuthContentRoute: typeof AuthContentRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDealerRoute: typeof AuthDealerRoute
  AuthDeliveryRoute: typeof AuthDeliveryRoute
  AuthDistributorRoute: typeof AuthDistributorRoute
  AuthFarmerRoute: typeof AuthFarmerRoute
  AuthMarketingRoute: typeof AuthMarketingRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSalesRoute: typeof AuthSalesRoute
  AuthSupportRoute: typeof AuthSupportRoute
  AuthWarehouseRoute: typeof AuthWarehouseRoute
  AuthWishlistRoute: typeof AuthWishlistRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountsRoute: AuthAccountsRoute,
  AuthContentRoute: AuthContentRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDealerRoute: AuthDealerRoute,
  AuthDeliveryRoute: AuthDeliveryRoute,
  AuthDistributorRoute: AuthDistributorRoute,
  AuthFarmerRoute: AuthFarmerRoute,
  AuthMarketingRoute: AuthMarketingRoute,
  AuthOrdersRoute: AuthOrdersRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSalesRoute: AuthSalesRoute,
  AuthSupportRoute: AuthSupportRoute,
  AuthWarehouseRoute: AuthWarehouseRoute,
  AuthWishlistRoute: AuthWishlistRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminContentRoute: AdminContentRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DealerRegistrationRoute: DealerRegistrationRoute,
  KnowledgeRoute: KnowledgeRoute,
  SigninRoute: SigninRoute,
  TrackRoute: TrackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BlogSlugRoute: BlogSlugRoute,
  LegalPageRoute: LegalPageRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
